### ISSUE TITLE
[Add Map] CO-OP VS 3 US Generals Challenge

### ISSUE THREAD

**Issue by Redeemer21** [MahBoiDeveloper/ZeroHourWorld#269] opened 2024-08-05 13:45 UTC
### Map Name

CO-OP VS 3 US Generals Challenge

### Map Kind

Cooperative Mission

### Author

[Dun淼咕]

### Author Contact

(https://www.moddb.com/members/sxandun)

### Download Link

https://www.moddb.com/games/cc-generals-zero-hour/addons/co-op-vs-3-us-generals-challengespecial-edition

**Comment by MahBoiDeveloper** [comment] 2024-08-06 06:36
Duplicate of #2

**Closed by MahBoiDeveloper** 2024-08-06 06:36 UTC
Labels: Add Map
